# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import CloudError, CloudErrorException
    from ._models_py3 import CloudErrorBody
    from ._models_py3 import TestGetResult
    from ._models_py3 import TestPutResult
except (SyntaxError, ImportError):
    from ._models import CloudError, CloudErrorException
    from ._models import CloudErrorBody
    from ._models import TestGetResult
    from ._models import TestPutResult

__all__ = [
    'CloudError', 'CloudErrorException',
    'CloudErrorBody',
    'TestGetResult',
    'TestPutResult',
]
